- hosts: vftd
  connection: local
  tasks:
    - name: Obtain access token
      ftd_oauth_token:
        device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
        username: '{{ username }}'
        password: '{{ password }}'
        operation: 'request'

    - name: Download files
      block:
        - name: Download pending changes
          ftd_download:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            object_type: 'pendingChanges'
            object_id: 'default'
            dest: /tmp/

        - name: Upload disk file
          ftd_upload:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            object_type: 'diskFile'
            src: /tmp/test.txt
            register_as: diskFile

        - name: Download disk file
          ftd_download:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            object_type: 'diskFile'
            object_id: "{{ diskFile['id'] }}"
            dest: /tmp/test2.txt

      always:
        - name: Revoke access token
          ftd_oauth_token:
            device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            operation: 'revoke'
