- hosts: vftd
  connection: local
  tasks:
    - name: Obtain access token
      fdm_oauth_token:
        device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
        username: 'admin'
        password: '123qwe'
        operation: 'request'

    - name: Managing configuration objects
      block:
        - name: Create a network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            operation: 'upsertNetworkObject'
            name: "Ansible-network-host"
            description: "From Ansible with love"
            subType: "HOST"
            value: "192.22.22.24"
            type: "networkobject"

            register_as: "networkObj1"

        - name: Fetch default Access Policy
          fdm_access_policy:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            filter: "name:Default Access Policy"
            limit: 1

            operation: "getAccessPolicyList"
            register_as: "accessPolicies"

        - name: Create an access rule
          fdm_access_rule:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            operation: 'upsertAccessRule'
            name: "Ansible-accessrule"
            type: "accessrule"
            parentId: "{{ accessPolicies[0]['id'] }}"
            sourceNetworks:
              - "{{ networkObj1 }}"

            register_as: "accessRule1"

        - name: Update the access rule
          fdm_access_rule:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            operation: 'editAccessRuleByName'
            name: "Ansible-accessrule"
            type: "accessrule"
            parentId: "{{ accessPolicies[0]['id'] }}"
            destinationNetworks:
              - "{{ networkObj1 }}"

            register_as: "accessRule1"

        - name: Deploy changes
          fdm_deploy:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

        - name: Delete an access rule
          fdm_access_rule:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            operation: 'deleteAccessRuleByName'
            name: 'Ansible-accessrule'
            parentId: "{{ accessPolicies[0]['id'] }}"

        - name: Delete a network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'deleteNetworkObject'
            objId: "{{ networkObj1['id'] }}"

      always:
        - name: Revoke access token
          fdm_oauth_token:
            device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            operation: 'revoke'
