- hosts: vftd
  connection: httpapi
  tasks:
    - name: Create a network object
      ftd_network_object:
        name: "Ansible-network-host"
        description: "From Ansible with love"
        subType: "HOST"
        value: "{{ access_rule_source_ip }}"
        type: "networkobject"

    - name: Create an access rule
      ftd_access_rule:
        name: "Ansible-accessrule"
        type: "accessrule"
        parentId: "default"
        sourceNetworks:
          - "{{ networkobject_ansible_network_host }}"

    - name: Update the access rule
      ftd_access_rule:
        operation: 'editAccessRuleByName'
        name: "Ansible-accessrule"
        type: "accessrule"
        parentId: "default"
        destinationNetworks:
          - "{{ networkobject_ansible_network_host }}"

    - name: Deploy changes
      ftd_deployment:

    - name: Delete an access rule
      ftd_access_rule:
        operation: 'deleteAccessRuleByName'
        name: 'Ansible-accessrule'
        parentId: "default"

    - name: Delete a network object
      ftd_network_object:
        operation: 'deleteNetworkObject'
        objId: "{{ networkobject_ansible_network_host['id'] }}"
