- hosts: vftd
  connection: local
  tasks:
    - name: Obtain access token
      fdm_oauth_token:
        device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
        username: '{{ username }}'
        password: '{{ password }}'
        operation: 'request'

    - name: Download files
      block:
        - name: Download pending changes using native Ansible module
          get_url:
            url: "{{ protocol }}://{{ ip_address }}:{{ port }}/api/fdm/v1/action/pendingchanges/download/default"
            dest: /tmp/pending_changes.yml
            headers: 'Authorization:Bearer {{ access_token }}'

        - name: Download pending changes using custom FDM module
          fdm_download:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

            object_type: 'pendingChanges'
            object_id: 'default'
            dest_file: /tmp/pending_changes2.yml

#        - name: Upload pending changes file to S3 with native Ansible module
#          aws_s3:
#            bucket: fdm
#            object: /fdm/pending_changes.yml
#            src: /tmp/pending_changes.yml
#            mode: put

      always:
        - name: Revoke access token
          fdm_oauth_token:
            device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            operation: 'revoke'
