- hosts: vftd
  connection: local
  tasks:
    - name: Obtain access token
      fdm_oauth_token:
        device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
        username: '{{ username }}'
        password: '{{ password }}'
        operation: 'request'

    - name: Managing configuration objects
      block:
        - name: Create a HOST network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'upsertNetworkObject'
            name: "Ansible-network-host"
            description: "From Ansible with love"
            subType: "HOST"
            value: "192.22.22.24"
            type: "networkobject"
            register_as: "networkObj1"

        - name: Create a NETWORK network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'upsertNetworkObject'
            name: "Ansible-network-network"
            description: "From Ansible with love"
            subType: "NETWORK"
            value: "192.23.23.0/24"
            type: "networkobject"
            register_as: "networkObj2"

        - name: Create a network group
          fdm_network_object_group:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'upsertNetworkObjectGroup'
            name: "Ansible-network-group"
            description: "From Ansible with love"
            type: "networkobjectgroup"
            objects:
              - "{{ networkObj1 }}"
              - "{{ networkObj2 }}"
            register_as: "networkGroup1"

        - name: Update the HOST network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'editNetworkObjectByName'
            name: "Ansible-network-host"
            description: "From Ansible with love. Version2"
            value: "192.22.22.25"
            subType: "HOST"
            type: "networkobject"
            register_as: "networkObj1"

        - name: Deploy changes
          fdm_deploy:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'

        - name: Refresh a NETWORK network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'getNetworkObjectByName'
            name: "Ansible-network-network"
            register_as: "networkObj2"

        - name: Update the network group
          fdm_network_object_group:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'editNetworkObjectGroupByName'
            name: "Ansible-network-group"
            description: "From Ansible with love. Version 2"
            type: "networkobjectgroup"
            objects:
              - "{{ networkObj2 }}"
            register_as: "networkGroup1"

        - name: Delete a network group
          fdm_network_object_group:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'deleteNetworkObjectGroup'
            objId: "{{ networkGroup1['id'] }}"

        - name: Delete a HOST network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'deleteNetworkObject'
            objId: "{{ networkObj1['id'] }}"

        - name: Delete a NETWORK network object
          fdm_network_object:
            hostname: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            refresh_token: '{{ refresh_token }}'
            operation: 'deleteNetworkObjectByName'
            name: "Ansible-network-network"

      always:
        - name: Revoke access token
          fdm_oauth_token:
            device_url: "{{ protocol }}://{{ ip_address }}:{{ port }}"
            access_token: '{{ access_token }}'
            operation: 'revoke'
