- name: "Test VMware deployment of vFTD"
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "vmware.api.host.com"
    vcenter_username: "username"
    vcenter_password: "username"
    vcenter_datacenter: "dc.name"
    vcenter_resource_pool: "some.resource.pool"
    vcenter_folder_name: "some.folder.name"
    mgmt_network_name: "some.network.name"
    new_vm_name: "Test_vFTD"
    new_passwd: "customPasswd"
    ftd_version: "6.4.0-1304"
  tasks:
    - name: "Download OVF"
      get_url:
        url: "https://some.file/server/Cisco_Firepower_Threat_Defense_Virtual-VI-{{ ftd_version }}.ovf"
        dest: "./"
        validate_certs: no
    - name: "Download VMDK"
      get_url:
        url: "https://some.file/server/Cisco_Firepower_Threat_Defense_Virtual-{{ ftd_version }}.vmdk"
        dest: "./"
        validate_certs: no
    - name: "Gather facts about datastore"
      vmware_datastore_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
      delegate_to: localhost
      register: datastores_list
    - name: "Create vFTD VM"
      vmware_deploy_ovf:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        resource_pool: "{{ vcenter_resource_pool }}"
        datastore: "{{ ( datastores_list.datastores | sort(attribute='freeSpace') | last).name }}"
        disk_provisioning: thin
        fail_on_spec_warnings: no
        folder: "{{ vcenter_folder_name }}"
        name: "{{ new_vm_name }}"
        ovf: "./Cisco_Firepower_Threat_Defense_Virtual-VI-{{ ftd_version }}.ovf"
        power_on: true
        wait: true
        networks:
          Management0-0: "{{ mgmt_network_name }}"
        properties:
          # Zero Day config defined with the following properties:
          # - pw
          # - fqdn
          # - dns1
          # - dns2
          # - dns3
          # - searchdomains
          # - ipv4.how
          # - ipv4.addr
          # - ipv4.mask
          # - ipv4.gw
          # - ipv6.how
          # - ipv6.addr
          # - ipv6.mask
          # - ipv6.gw
          # - manageLocally
          # - firewallmode
          # - mgr
          # - regkey
          # - regNAT
          pw: "{{ new_passwd }}"

        wait_for_ip_address: yes
      delegate_to: localhost
    - name: "Destroy vFTD VM"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ new_vm_name }}"
        force: yes
        state: absent
      delegate_to: localhost
