- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Install image v6.4.0 on FTD 2110
      cisco.ftdansible.ftd_install:
        device_hostname: firepower
        device_password: pass
        device_ip: 192.168.0.1
        device_netmask: 255.255.255.0
        device_gateway: 192.168.0.254
        dns_server: 8.8.8.8
        device_model: 'Cisco Firepower 2110 Threat Defense'

        console_ip: 10.89.0.0
        console_port: 2004
        console_username: console_user
        console_password: console_pass

        rommon_file_location: 'tftp://10.89.0.11/installers/fxos-k8-fp2k-lfbff.2.6.1.94i.SPA'
        image_file_location: 'tftp://10.89.0.11/installers/cisco-ftd-fp2k.6.4.0-1293.SPA'
        image_version: 6.4.0-1292
