- hosts: ftd
  connection: httpapi
  tasks:
    - name: Install image v6.3.0 on FTD 5516
      cisco.ftdansible.ftd_install:
        device_hostname: firepower
        device_password: pass
        device_ip: 192.168.0.1
        device_netmask: 255.255.255.0
        device_gateway: 192.168.0.254
        dns_server: 8.8.8.8

        console_ip: 10.89.0.0
        console_port: 2004
        console_username: console_user
        console_password: console_pass

        rommon_file_location: 'tftp://10.89.0.11/installers/ftd-boot-9.10.1.3.lfbff'
        image_file_location: 'https://10.89.0.11/installers/ftd-6.3.0-83.pkg'
        image_version: 6.3.0-83
