- hosts: vftd
  connection: httpapi
  tasks:
    - name: Create a network object
      ftd_config_entity:
        operation: "addNetworkObject"
        data:
          name: "Ansible-network-host"
          description: "From Ansible with love"
          subType: "HOST"
          value: "{{ access_rule_source_ip }}"
          type: "networkobject"

    - name: Create an access rule
      ftd_config_entity:
        operation: "addAccessRule"
        data:
          name: "Ansible-accessrule"
          type: "accessrule"
          sourceNetworks:
            - "{{ networkobject_ansible_network_host }}"
          ruleAction: "PERMIT"
          eventLogAction: "LOG_BOTH"
        path_params:
          parentId: "default"

    - name: Update the access rule
      ftd_config_entity:
        operation: 'editAccessRule'
        data:
          name: "Ansible-accessrule"
          id: "{{ accessrule_ansible_accessrule['id'] }}"
          ruleId: "{{ accessrule_ansible_accessrule['ruleId'] }}"
          version: "{{ accessrule_ansible_accessrule['version'] }}"
          type: "accessrule"
          destinationNetworks:
            - "{{ networkobject_ansible_network_host }}"
          ruleAction: "PERMIT"
          eventLogAction: "LOG_BOTH"
        path_params:
          objId: "{{ accessrule_ansible_accessrule['id'] }}"
          parentId: "default"

#    - name: Deploy changes
#      ftd_deployment:

    - name: Delete an access rule
      ftd_config_entity:
        operation: 'deleteAccessRule'
        path_params:
          objId: "{{ accessrule_ansible_accessrule['id'] }}"
          parentId: "default"

    - name: Delete a network object
      ftd_config_entity:
        operation: 'deleteNetworkObject'
        path_params:
          objId: "{{ networkobject_ansible_network_host['id'] }}"
