- hosts: vftd
  connection: httpapi
  tasks:
    - name: Check HA status
      ftd_ha_status:
        operation: 'getHAStatus'
        objId: "default"
        register_as: "ha_status"

    - debug:
        msg: "{{ ha_status }}"

    - name: Check HA configuration
      ftd_ha_configuration:
        operation: 'getHAConfigurationByName'
        name: 'HA'
        register_as: "ha_config"

    - debug:
        msg: "{{ ha_config }}"

    - name: Join HA configuration
      ftd_join_ha_status:

    - name: Break HA configuration
      ftd_break_ha_status:
