- hosts: localhost
  connection: local
  tasks:
  - name: Install image v6.2.3 on FTD
    ftd_install:
      device_hostname: firepower
      device_password: Sourcefire
      device_ip: 192.168.0.1
      device_netmask: 255.255.255.0
      device_gateway: 192.168.0.254
      dns_server: 8.8.8.8

      console_ip: 10.89.0.0
      console_port: 2004
      console_username: console_user
      console_password: console_pass

      image_site: ast
      image_branch: Release
      image_version: 6.2.3-83