- hosts: vftd
  connection: httpapi
  tasks:
    - name: Create a HOST network object
      ftd_configuration:
        operation: "upsertNetworkObject"
        data:
          name: "Ansible-network-host"
          description: "From Ansible with love"
          subType: "HOST"
          value: "{{ host_ip }}"
          isSystemDefined: False
          type: "networkobject"

    - name: Create a NETWORK network object
      ftd_configuration:
        operation: "upsertNetworkObject"
        data:
          name: "Ansible-network-network"
          description: "From Ansible with love"
          subType: "NETWORK"
          value: "{{ network_ip }}"
          type: "networkobject"

    - name: Create a network group
      ftd_configuration:
        operation: "upsertNetworkObjectGroup"
        data:
          name: "Ansible-network-group"
          description: "From Ansible with love"
          type: "networkobjectgroup"
          objects:
            - "{{ networkobject_ansible_network_host }}"
            - "{{ networkobject_ansible_network_network }}"

    - name: Update the HOST network object
      ftd_configuration:
        operation: 'editNetworkObject'
        path_params:
          objId: "{{ networkobject_ansible_network_host['id'] }}"
        data:
          id: "{{ networkobject_ansible_network_host['id'] }}"
          version: "{{ networkobject_ansible_network_host['version'] }}"
          name: "Ansible-network-host"
          description: "From Ansible with love. Version2"
          value: "192.22.22.25"
          subType: "HOST"
          type: "networkobject"

    - name: Refresh a NETWORK network object
      ftd_configuration:
        operation: 'getNetworkObject'
        path_params:
          objId: "{{ networkobject_ansible_network_host['id'] }}"

    - name: Update the network group
      ftd_configuration:
        operation: 'editNetworkObjectGroup'
        path_params:
          objId: "{{ networkobjectgroup_ansible_network_group['id'] }}"
        data:
          id: "{{ networkobjectgroup_ansible_network_group['id'] }}"
          version: "{{ networkobjectgroup_ansible_network_group['version'] }}"
          name: "Ansible-network-group"
          description: "From Ansible with love. Version 2"
          type: "networkobjectgroup"
          objects:
            - "{{ networkobject_ansible_network_network }}"

    - name: Delete a network group
      ftd_configuration:
        operation: 'deleteNetworkObjectGroup'
        path_params:
          objId: "{{ networkobjectgroup_ansible_network_group['id'] }}"

    - name: Delete a HOST network object
      ftd_configuration:
        operation: 'deleteNetworkObject'
        path_params:
          objId: "{{ networkobject_ansible_network_host['id'] }}"

    - name: Delete a NETWORK network object
      ftd_configuration:
        operation: 'deleteNetworkObject'
        path_params:
          objId: "{{ networkobject_ansible_network_network['id'] }}"
