- name: "Deploy new vFTD VM"
  hosts: kvm_hosts
  gather_facts: yes
  vars:
    hdd_path: '{{ vms_folder }}/{{ ftd_vm_name }}/hdd.qcow2'
    zero_day_config_file: "{{ vms_folder }}/{{ ftd_vm_name }}/day0-config"
    cdrom_path: '{{ vms_folder }}/{{ ftd_vm_name }}/cdrom.iso'
  tasks:
    - name: "Create VM dir"
      file:
        path: "{{ main_folder }}/kvm_hdds/{{ ftd_vm_name }}"
        state: directory
    - name: "Copy image file to hdd dir"
      copy:
        src: "{{ main_folder }}/images/vFTD-{{ ftd_build_id }}.qcow2"
        dest: "{{ hdd_path }}"
        remote_src: yes

    - name: "Copy image file to hdd dir"
      copy:
        dest: "{{ zero_day_config_file }}"
        content: |
          {"EULA": "accept",
          "Hostname": "kvm-vFTD",
          "AdminPassword": "TestPasswd",
          "FirewallMode": "routed",
          "DNS1": "8.8.8.8",
          "DNS2": "8.8.4.4",
          "DNS3": "",
          "IPv4Mode": "dhcp",
          "IPv4Addr": "",
          "IPv4Mask": "",
          "IPv4Gw": "",
          "IPv6Mode": "disabled",
          "IPv6Addr": "",
          "IPv6Mask": "",
          "IPv6Gw": "",
          "FmcIp": "",
          "FmcRegKey": "",
          "FmcNatId": ""}
    - name: "Generate ISO file"
      shell: "mkisofs -r -o {{ cdrom_path }} {{ zero_day_config_file }}"
    - name: "Define vm"
      virt:
          name: "{{ ftd_vm_name }}"
          command: define
          xml: "{{ lookup('template', './guest_template.xml') }}"
    - name: "Start vm"
      virt:
          name: "{{ ftd_vm_name }}"
          state: running
