- hosts: all
  connection: httpapi
  tasks:
    - name: Find an intrustion policy with maximum detection
      ftd_configuration:
        operation: getIntrusionPolicyList
        filters:
          name: Maximum Detection
        register_as: policies

    - name: Allow traffic with maximum detection by default
      ftd_configuration:
        operation: upsertAccessPolicy
        data:
          name: NGFW-Access-Policy
          defaultAction:
            action: PERMIT
            eventLogAction: LOG_NONE
            intrusionPolicy:
              id: "{{ policies[0]['id'] }}"
              type: "{{ policies[0]['type'] }}"
            type: accessdefaultaction
          type: accesspolicy
