- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      cisco.ftdansible.ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable Malware License
      cisco.ftdansible.ftd_configuration:
        operation: addLicense
        data:
          licenseType: MALWARE
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["MALWARE"]) | list | length == 0'

    - name: Enable Threat License
      cisco.ftdansible.ftd_configuration:
        operation: addLicense
        data:
          licenseType: THREAT
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["THREAT"]) | list | length == 0'

    - name: Find an intrustion policy
      cisco.ftdansible.ftd_configuration:
        operation: getIntrusionPolicyList
        register_as: intrusion_policies

    - name: Find a file policy
      cisco.ftdansible.ftd_configuration:
        operation: getFilePolicyList
        register_as: file_policies

    - name: Create an access rule with intrusion and file policies
      cisco.ftdansible.ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Intrusion and file policy rule
          ruleAction: PERMIT
          filePolicy: "{{ file_policies[0] }}"
          intrusionPolicy:
            id: "{{ intrusion_policies[0].id }}"
            type: "{{ intrusion_policies[0].type }}"
          type: accessrule
        path_params:
          parentId: default
