- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      cisco.ftdansible.ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable Malware License
      cisco.ftdansible.ftd_configuration:
        operation: addLicense
        data:
          licenseType: MALWARE
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["MALWARE"]) | list | length == 0'

    - name: Find a file policy
      cisco.ftdansible.ftd_configuration:
        operation: getFilePolicyList
        register_as: file_policies

    - name: Setup a syslog server
      cisco.ftdansible.ftd_configuration:
        operation: upsertSyslogServer
        data:
          name: 10.0.4.5:514
          useManagementInterface: True
          protocol: UDP
          host: 10.0.4.5
          port: "514"
          type: syslogserver
        filters:
          host: 10.0.4.5
        register_as: syslog_server

    - name: Create an access rule logging malware files
      cisco.ftdansible.ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Log traffic with malware files
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
          filePolicy: "{{ file_policies[0] }}"
          syslogServer: "{{ syslog_server }}"
          type: accessrule
        path_params:
          parentId: default
