- hosts: all
  connection: httpapi
  tasks:
    - name: Create an FQDN network for Cisco DevNet
      ftd_configuration:
        operation: addNetworkObject
        data:
          name: CiscoDevNetNetwork
          subType: FQDN
          value: developer.cisco.com
          isSystemDefined: False
          type: networkobject
          dnsResolution: IPV4_AND_IPV6
                  
    - name: Create an access rule allowing trafic from Cisco DevNet
      ftd_configuration:
        operation: addAccessRule
        data:
          name: AllowCiscoTraffic
          type: accessrule
          sourceNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
        path_params:
          parentId: default

    - name: Update the access rule to allow trafic from/to Cisco DevNet
      ftd_configuration:
        operation: editAccessRule
        data:
          name: AllowCiscoTraffic
          id: '{{ accessrule_allowciscotraffic.id }}'
          ruleId: '{{ accessrule_allowciscotraffic.ruleId }}'
          version: '{{ accessrule_allowciscotraffic.version }}'
          type: accessrule
          sourceNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          destinationNetworks:
            - '{{ networkobject_ciscodevnetnetwork }}'
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
        path_params:
          objId: '{{ accessrule_allowciscotraffic.id }}'
          parentId: default

    - name: Delete the access rule allowing trafic from/to Cisco DevNet
      ftd_configuration:
        operation: deleteAccessRule
        path_params:
          objId: '{{ accessrule_allowciscotraffic.id }}'
          parentId: default

    - name: Delete the FQDN network for Cisco DevNet
      ftd_configuration:
        operation: deleteNetworkObject
        path_params:
          objId: '{{ networkobject_ciscodevnetnetwork.id }}'
