- hosts: all
  connection: httpapi
  tasks:
    - name: Check Licenses
      cisco.ftdansible.ftd_configuration:
        operation: getLicenseList
        register_as: all_license_list

    - name: Enable URL License
      cisco.ftdansible.ftd_configuration:
        operation: addLicense
        data:
          licenseType: URLFILTERING
          type: license
          count: 1
      when: 'all_license_list | selectattr("licenseType", "in", ["URLFILTERING"]) | list | length == 0'

    - name: Find an URL category
      cisco.ftdansible.ftd_configuration:
        operation: getURLCategoryList
        register_as: category_results

    - name: Find a high risk URL reputation
      cisco.ftdansible.ftd_configuration:
        operation: getURLReputationList
        filters:
          startPercentage: 1
        register_as: reputation_results

    - name: Create an access rule blocking traffic
      cisco.ftdansible.ftd_configuration:
        operation: upsertAccessRule
        data:
          name: Block traffic from alcohol URLs with high risks
          ruleAction: DENY
          eventLogAction: LOG_NONE
          urlFilter:
            urlCategories:
              - type: urlcategorymatcher
                urlCategory: "{{ category_results[0] }}"
                urlReputation: "{{ reputation_results[0] }}"
            urlObjects: []
            type: embeddedurlfilter
          type: accessrule
        path_params:
          parentId: default
