- hosts: all
  connection: httpapi
  tasks:
    - name: Fetch pending changes
      cisco.ftdansible.ftd_configuration:
        operation: getBaseEntityDiffList
        register_as: pending_changes

    - name: Complete playbook when nothing to deploy
      meta: end_play
      when: pending_changes | length == 0

    - name: Start deployment
      cisco.ftdansible.ftd_configuration:
        operation: addDeployment
        register_as: deployment_job

    - name: Poll deployment status until the job is finished
      cisco.ftdansible.ftd_configuration:
        operation: getDeployment
        path_params:
          objId: '{{ deployment_job.id }}'
        register_as: deployment_status
      until: deployment_status.endTime != -1
      retries: 100
      delay: 3

    - name: Stop the playbook if the deployment failed
      fail:
        msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
      when: deployment_status.state != 'DEPLOYED'
