- hosts: all
  connection: httpapi
  tasks:
    - name: Get provisioning info
      ftd_configuration:
        operation: getInitialProvision
        path_params:
          objId: default
        register_as: provisionInfo

    - name: Show EULA text
      debug:
        msg: "EULA details: {{ provisionInfo['eulaText'] }}"

    - name: Confirm EULA acceptance
      pause:
        prompt: 'Please confirm you want to accept EULA. Press Return to continue. To abort, press Ctrl+C and then "A"'

    - name: Complete initial provisioning
      ftd_configuration:
        operation: addInitialProvision
        data:
          acceptEULA: True
          eulaText: "{{ provisionInfo['eulaText'] }}"
          currentPassword: "oldPassword"
          newPassword: "newPassword1$"
          type: initialprovision
