- hosts: all
  connection: httpapi
  tasks:
    - name: Create an FQDN network for Cisco DevNet
      cisco.ftdansible.ftd_configuration:
        operation: upsertNetworkObject
        data:
          name: CiscoDevNetNetwork
          subType: FQDN
          value: developer.cisco.com
          type: networkobject
          dnsResolution: IPV4_AND_IPV6

    - name: Create an FQDN network for Cisco FTD
      cisco.ftdansible.ftd_configuration:
        operation: upsertNetworkObject
        data:
          name: CiscoFtdNetwork
          subType: FQDN
          value: ftd.cisco.com
          type: networkobject
          dnsResolution: IPV4_AND_IPV6

    - name: Create a Cisco network group
      cisco.ftdansible.ftd_configuration:
        operation: upsertNetworkObjectGroup
        data:
          name: CiscoNetworkGroup
          type: networkobjectgroup
          objects:
          - '{{ networkobject_ciscodevnetnetwork }}'
          - '{{ networkobject_ciscoftdnetwork }}'

    - name: Update the FQDN network for Cisco FTD
      cisco.ftdansible.ftd_configuration:
        operation: editNetworkObject
        path_params:
          objId: '{{ networkobject_ciscoftdnetwork.id }}'
        data:
          id: '{{ networkobject_ciscoftdnetwork.id }}'
          version: '{{ networkobject_ciscoftdnetwork.version }}'
          name: CiscoFtdNetwork
          description: Updated version
          value: 192.22.22.25
          subType: HOST
          type: networkobject

    - name: Update the Cisco network group by removing FTD network
      cisco.ftdansible.ftd_configuration:
        operation: editNetworkObjectGroup
        path_params:
          objId: '{{ networkobjectgroup_cisconetworkgroup.id }}'
        data:
          id: '{{ networkobjectgroup_cisconetworkgroup.id }}'
          version: '{{ networkobjectgroup_cisconetworkgroup.version }}'
          name: CiscoNetworkGroup
          type: networkobjectgroup
          objects:
            - '{{ networkobject_ciscodevnetnetwork }}'

    - name: Delete the Cisco network group
      cisco.ftdansible.ftd_configuration:
        operation: deleteNetworkObjectGroup
        path_params:
          objId: '{{ networkobjectgroup_cisconetworkgroup.id }}'

    - name: Delete the FQDN network for Cisco DevNet
      cisco.ftdansible.ftd_configuration:
        operation: deleteNetworkObject
        path_params:
          objId: '{{ networkobject_ciscodevnetnetwork.id }}'

    - name: Delete the FQDN network for Cisco FTD
      cisco.ftdansible.ftd_configuration:
        operation: deleteNetworkObject
        path_params:
          objId: '{{ networkobject_ciscoftdnetwork.id }}'