- hosts: all
  connection: httpapi
  vars:
    iface_name: "inside"
    iface_hardware_name: "GigabitEthernet0/1"
  tasks:
    - name: Get List of DHCP servers
      ftd_configuration:
        operation: "getDHCPServerContainerList"
        register_as: dhcp_containers_list

    - name: Execute 'editDHCPServerContainer' operation
      ftd_configuration:
        operation: "editDHCPServerContainer"
        data:
            name: "{{ dhcp_containers_list.0.name }}"
            version: "{{ dhcp_containers_list.0.version }}"
            autoConfig: "{{ dhcp_containers_list.0.autoConfig }}"
            primaryDNS: "{{ dhcp_containers_list.0.primaryDNS }}"
            secondaryDNS: "{{ dhcp_containers_list.0.secondaryDNS }}"
            primaryWINS: "{{ dhcp_containers_list.0.primaryWINS }}"
            secondaryWINS: "{{ dhcp_containers_list.0.secondaryWINS }}"
            servers: '{{ dhcp_containers_list.0.servers | selectattr("interface.name", "ne", iface_name) | list }}'
            interface: "{{ dhcp_containers_list.0.interface }}"
            type: "{{ dhcp_containers_list.0.type }}"
        path_params:
            objId: "{{ dhcp_containers_list.0.id }}"

    - name: Setup Inside Interface with static IP
      ftd_configuration:
        operation: upsertPhysicalInterface
        data:
          name: "{{iface_name}}"
          hardwareName: "{{iface_hardware_name}}"
          monitorInterface: True
          ipv4:
            addressNull: False
            defaultRouteUsingDHCP: False
            dhcp: False
            ipAddress:
              ipAddress: 192.168.20.2
              netmask: 255.255.255.0
              standbyIpAddress: 192.168.20.3
              type: haipv4address
            ipType: STATIC
            type: interfaceipv4
          mtu: 1500
          enabled: True
          mode: ROUTED
          type: physicalinterface
        filters:
          hardwareName: "{{iface_hardware_name}}"
