- hosts: all
  connection: httpapi
  tasks:
    - name: Create a TCP port for PostgreSQL
      cisco.ftdansible.ftd_configuration:
        operation: upsertTCPPortObject
        data:
          name: PostgreSQL port
          port: "5432"
          type: tcpportobject

    - name: Create a TCP port for MySQL
      cisco.ftdansible.ftd_configuration:
        operation: upsertTCPPortObject
        data:
          name: MySQL port
          port: "3306"
          type: tcpportobject

    - name: Create a database port group
      cisco.ftdansible.ftd_configuration:
        operation: upsertPortObjectGroup
        data:
          name: Database ports
          objects:
            - "{{ tcpportobject_mysql_port }}"
            - "{{ tcpportobject_postgresql_port }}"
          type: portobjectgroup

    - name: Create a UDP port for NTP protocol
      cisco.ftdansible.ftd_configuration:
        operation: upsertUDPPortObject
        data:
          name: NTP port
          port: "123"
          type: udpportobject

    - name: Create an object for ICMP Time Exceeded type
      cisco.ftdansible.ftd_configuration:
        operation: upsertICMPv4PortObject
        data:
          name: ICMP Time Exceeded
          icmpv4Type: TIME_EXCEEDED
          icmpv4Code: TTL_EXPIRED_TRANSIT
          type: icmpv4portobject
