- name: Setup SmartAgent
  import_playbook: smart_license.yml

- name: Setup required license
  import_playbook: ra_vpn_license.yaml

- name: Setup AnyConnect VPN package file
  import_playbook: anyconnect_package_file.yml

- hosts: all
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Get Anyconnect Package Files
    cisco.ftdansible.ftd_configuration:
      operation: getAnyConnectPackageFileList
      register_as: all_anyconnect_package_files

  - name: Get Phisical Interfaces
    cisco.ftdansible.ftd_configuration:
      operation: getPhysicalInterfaceList
      register_as: all_phisical_interfaces

  - name: Get Internal Certificates
    cisco.ftdansible.ftd_configuration:
      operation: getInternalCertificateList
      register_as: all_internal_certificates

  - name: Get RA VPN Group Policy
    cisco.ftdansible.ftd_configuration:
      operation: getRaVpnGroupPolicyList
      register_as: all_ravpn_group_policy_list

  - name: Get Local Identity Sources
    cisco.ftdansible.ftd_configuration:
      operation: getLocalIdentitySourceList
      register_as: all_local_identity_sources

  - name: Create RA VPN
    cisco.ftdansible.ftd_configuration:
      operation: upsertRaVpn
      data:
        name: NGFW-Remote-Access-VPN # NOTE: this name is ignored on backend
        vpnGatewaySettings:
          outsideInterface: '{{ all_phisical_interfaces | selectattr("name", "eq", "outside") | list | first }}'
          serverCertificate: '{{ all_internal_certificates | first }}'
          exemptNatRule: false
          bypassAccessControlForVPNTraffic: false
          clientCACertificates: []
          insideInterfaces: []
          insideNetworks: []
          outsideFqdn: "{{inventory_hostname}}.cisco.com"
          type: vpngatewaysettings
        groupPolicies:
        - '{{ all_ravpn_group_policy_list | first }}'
        anyconnectPackageFiles:
        - '{{ all_anyconnect_package_files | first }}'
        type: ravpn
      register_as: ra_vpn

  - name: Create RA VPN Connection Profile
    cisco.ftdansible.ftd_configuration:
      operation: upsertRaVpnConnectionProfile
      data:
        name: 'ra_vpn_connection_profile_{{inventory_hostname}}'
        defaultGroupPolicy: '{{ all_ravpn_group_policy_list | first }}'
        authMethod: AAA
        stripGroupFromUsername: False
        stripRealmFromUsername: False
        authenticationIdentitySource: '{{all_local_identity_sources | first}}'
        type: ravpnconnectionprofile
      path_params:
        parentId: '{{ra_vpn.id}}'
      register_as: ra_vpn_connection_profile
