- hosts: vftd
  connection: local
  tasks:
    - name: Obtain access token
      fdm_oauth_token:
        device_url: "https://{{ ip_address }}:{{ port }}"
        username: '{{ username }}'
        password: '{{ password }}'
        operation: 'request'

    - name: Managing configuration objects
      block:
        - name: Test that ansible can create a network object with HOST subtype
          fdm_nw:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-network-host"
            description: "From Ansible with love"
            sub_type: "HOST"
            value: "192.22.22.21"
            operation: "create"
        - name: Test that ansible can create a NETWORK network object
          fdm_nw:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-network-network"
            description: "From Ansible with love"
            sub_type: "NETWORK"
            value: "192.23.23.0/24"
        - name: Test that ansible can delete a network object with HOST subtype
          fdm_nw:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-network-host"
            description: "From Ansible with love"
            sub_type: "HOST"
            value: "192.22.22.21"
            operation: "delete"
        - name: Test that ansible can update silently a NETWORK network object
          fdm_nw:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-network-network"
            description: ""
            sub_type: "NETWORK"
            value: "192.23.23.0/24"
        - name: Test that ansible can create/update silently a NETWORK network object
          fdm_nw:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-network-network-2"
            description: "From Ansible with love-2"
            sub_type: "NETWORK"
            value: "192.43.23.0/24"
        - name: Test that ansible can create an access rule
          fdm_ar:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-accessrule"
            source_networks: ["networks.Ansible-network-network-2"]
            operation: "create"
        - name: Test that ansible can update an access rule
          fdm_ar:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-accessrule"
            operation: "update"
            source_networks: ["networks.Ansible-network-network"]
        - name: Test that ansible can update an access rule
          fdm_ar:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-accessrule"
            operation: "update"
            destination_networks: ["networks.Ansible-network-network-2"]
        - name: Test that ansible can delete an access rule
          fdm_ar:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            name: "Ansible-accessrule"
            operation: "delete"
      always:
        - name: Revoke access token
          fdm_oauth_token:
            device_url: "https://{{ ip_address }}:{{ port }}"
            token: '{{ access_token }}'
            operation: 'revoke'
